# Generated by Django 6.0 on 2025-12-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_appointmentmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
