# Generated by Django 6.0 on 2025-12-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_profilemodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
