# Generated by Django 6.0 on 2025-12-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_profilemodel_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='number',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='doctormodel',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
