# Generated by Django 6.0 on 2026-01-08 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_appointment_done_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentmodel',
            old_name='Patient',
            new_name='patient',
        ),
    ]
