# Generated by Django 6.0 on 2026-01-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_rename_patient_appointmentmodel_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment_done_model',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
