# Generated by Django 6.0 on 2026-01-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_appointment_done_model_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmodel',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
