# Generated by Django 6.0 on 2026-01-08 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_appointmentmodel_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment_done_model',
            name='status',
        ),
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='status',
        ),
    ]
