# Generated by Django 6.0 on 2026-01-08 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_remove_appointment_done_model_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment_done_model',
            old_name='Patient',
            new_name='patient',
        ),
    ]
