# Generated by Django 6.0 on 2026-01-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_rename_patient_appointment_done_model_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmodel',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
