# Generated by Django 6.0 on 2026-01-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_appointmentmodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='status',
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
