# Generated by Django 6.0 on 2026-01-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_remove_appointmentmodel_status_doctormodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='email',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='address',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
