# Generated by Django 6.0 on 2026-01-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0014_profilemodel_email_alter_profilemodel_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
