# Generated by Django 6.0 on 2026-01-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_alter_profilemodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='prof_pic'),
        ),
    ]
